---
directory: ~/Music/ext-music
library: ~/.config/beets/library.db
musicbrainz:
        match:
                ignored_media: ['Data CD', 'DVD', 'DVD-Video', 'Blu-ray',
                                'HD-DVD', 'VCD', 'SVCD', 'UMD', 'VHS']
ui:
        color: yes
        colors:
                text_success: green
                text_warning: yellow
                text_error: red
                text_highlight: red
                text_highlight_minor: lightgray
                action_default: turquoise
                action: blue
import:
        move: yes
        copy: no
        autotag: yes
plugins: [mpdstats, embedart, fetchart, convert, info, chroma, fuzzy, zero, discogs]
replaygain:
        backend: bs1770gain
        method: ebu
        r128: [Opus, MP3, FLAC, AAC, ALAC, Wave]
embedart:
        ifempty: yes
        remove_art_file: yes
mpd:
        music_directory: ~/Music/ext-music
chroma:
        auto: yes
zero:
        fields: comments genre
        update_database: true
discogs:
        user_token: <ACCESS_TOKEN_FROM_DISCOGS>
