# Specifies the network interface to use for the LocalIP readout
interface = "wlp7s0"

# Lengthen uptime output
long_uptime = true

# Lengthen shell output
long_shell = false

# Lengthen kernel output
long_kernel = true

# Toggle between displaying the current shell or your user's default one.
current_shell = true

# Toggle between displaying the number of physical or logical cores of your
# processor.
physical_cores = true

theme = "Nova"

# Displays only the specified readouts.
# Accepted values (case-sensitive):
#   - Host
#   - Machine
#   - Kernel
#   - Distribution
#   - OperatingSystem
#   - DesktopEnvironment
#   - WindowManager
#   - Resolution
#   - Backlight
#   - Packages
#   - LocalIP
#   - Terminal
#   - Shell
#   - Uptime
#   - Processor
#   - ProcessorLoad
#   - Memory
#   - Battery

show = [
  "Machine",
  "Kernel",
  "Distribution",
  "Packages",
  "OperatingSystem",
  "DesktopEnvironment",
  "WindowManager",
  "Shell",
  "Memory",
  "Uptime",
]

